# Generated by Django 5.1 on 2024-08-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.CharField(max_length=66, primary_key=True, serialize=False)),
                ('freeSize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.CharField(max_length=66, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.CharField(max_length=66, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=40)),
            ],
        ),
    ]
