# Generated by Django 5.1 on 2025-04-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='total_remaining_collateral',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
